name: Deploy Pages
run-name: Deploying pages
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1
        uses: actions/checkout@v4
      - name: 2
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: 3
        run: npm install
      - name: 4
        run: npm run build
      - name: 5
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4